### ISSUE TITLE
Dodelat hudebni prehravac.

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-android#154]

**Comment by rzeh4n** [comment]
Změna aktivity (vynechání úrovně sound_unit), přehrávání na pozadí a notifikace v a21e39145cf2181ee5b9f2b121384b6a6724bf45 až aac9b75bb13d4e0b7f326e725936b58c2b785c4f. Ještě zbývá zobrazování obrázků pro sound_recording a sound_unit.

**Comment by zabak** [comment]
Pokud něco přehrávám (resp. přehraju kousek a zapauzuju) a něco zabije aplikaci, tak v notifikacích zůstane pořád skladba zobrazená, nejde ale přehrát, nic se neděje.

**Comment by rzeh4n** [comment]
Samotný přehrávač dodělaný je. Ty zbylé věci jsem rozdělil na 2 issue.
