### ISSUE TITLE
video z tabletu

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-android#200]
Prosím o video z 10" tabletu - čtení knihy a čtení novin - nějakých co jsou naskenovány barevně a v imageserveru, ať to vypadá hezky.

**Comment by honza-rychtar** [comment]
Videa dve byt nemuzou. Pokud mame pouzity screen recording, tak je to nejlepsi z telefonu.
Screenshoty upravim. Stranka z lidovek je tam pro telefony a 7" tablet, ale ne na 10"
