### ISSUE TITLE
Pokud je rocnik pripojen pod dve ruzna periodika, tak aplikace spadne pri nacitani stranky

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-android#212]
V takovem pripade ma item dva kontexty:
"context" : [[x1,x2,x3],[y1,y2,y3]]
Predpoklada se, ze je vzdy jeden kontext a v tomto pripade se hierarchive vrati jako null a spadne to.
Pokud jde o chybu v datech a takove situace nejsou pripustne, pak jen odchytit ten null a zpracovat to jako spatne nacteni dat.
Pokud jsou dva kontexty pripustne, pak zmenit zpusob nacitani hierarchie.

**Comment by MartinRumanek** [comment]
U model:article je taková situace plně korektní - http://kramerius.mzk.cz/search/api/v5.0/item/uuid:126bc200-f5bd-11df-be2d-00016c4ba98b - 5 kontextů.

**Comment by honza-rychtar** [comment]
Opraveno, veme se prvni kontext.
