### ISSUE TITLE
Změnit text "O aplikaci"

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-android#223]
Aplikace zpřístupňuje digitální fondy českých knihoven využívajících systém Kramerius. Najdete zde dokumenty, které již nepodléhají autorskému zákonu - beletrii, staré noviny a časopisy, archiválie, rukopisy, kolekce map, digitalizované gramodesky a další. V menu si můžete vybrat, které dokumenty z jaké knihovny chcete prohlížet.

Máte-li jakékoliv připomínky, otázky nebo nápady, kontaktujte nás prosím na developer@mzk.cz.

Aplikaci vyvíjí Moravská zemská knihovna v Brně.

**Comment by LenkaDamborska** [comment]
Teď jsme se shodli s Jirkou, že by tam mělo být v první větě "využívající". Anebo tam můžeme dát, ",které využívají.." .

**Comment by honza-rychtar** [comment]
Zmeni jsem to na:
**cs**
Aplikace zpřístupňuje digitální fondy českých knihoven.
Najdete zde dokumenty, které již nepodléhají autorskému zákonu - beletrii, staré noviny a časopisy, archiválie, rukopisy, kolekce map, gramodesky a další.

Máte-li jakékoliv připomínky, otázky nebo nápady, kontaktujte nás prosím na [developer@mzk.cz](mailto:developer@mzk.cz).

Aplikaci vyvíjí [Moravská zemská knihovna v Brně](http://www.mzk.cz).

**en**
The application provides access to digital documents of Czech libraries.
You can find here documents that are no longer subject to copyright law - literature, old newspapers and magazines, archives, manuscripts, map collections, LPs and more.

If you have any comments, questions or suggestions, please contact us at [developer@mzk.cz.](mailto:developer@mzk.cz).

The application is developed by the [Moravian Library in Brno](http://www.mzk.cz/).


Zminku o pouzivani systemu Kramerius jsem odstranil - kdo Krameria zna, tomu je to jasne. Pro ostatni je to matouci - Kramerius je pro ne tato aplikace, co je to pak *System Kramerius*??
Muze byt?

**Comment by LenkaDamborska** [comment]
Tak Kramerius je systém :) Ale o to nejde. Chtěla jsem jen rozlišit, o jaké digitální fondy jde. Knihovny mají totiž další digitalizovaná díla, která se zpřístupňují jiným způsobem než v Krameriu.

**Comment by honza-rychtar** [comment]
Jde o to, pro koho je text urceny.
Pokud chcete aplikaci dostat k co nejvice lidem, tak je potreba ji propagovat jinym zpusobem. 
V prve rade nesnazit se psat texty a pojmy jakoby pro knihovniky, administratory, informovane studenty ....Vykaslat se na formality, nucenou presnost a vysvetlovani vseho.
99.9% lidi, kteri na Play muzou na aplikaci narazit, vubec netusi co je to Kramerius, 90 % nema predstavu co je to digitalni knihovna. Lidi nezajima proc tam neco neni kvuli autorskeho zakona, ani ze najaky autorsky zakon existuje. Je jim jedno odkud se data tahaji, ....

Je potreba predpokladat, ze texty (zejmena ty na Play) nebudou cist knihovnici, studenti, badatele, dokonce ani uzivatele Krameria - ale *mozne* uzivatele Krameria. A pro ty bude poutavejsi napsat "tisice knih zdarma", nez je znudit recmi o autorskem zakone a typech pondu :) 
Uz tu prvni vetu si prumerny uzivatel Google Play bude muset precit 3x, aby to pochopil - coz k instalaci nepovede.
Tohle se tyka spis popisu na Play nez textu v "O aplikaci" - tam je ale ten text podobny.

**Comment by LenkaDamborska** [comment]
Jo, počkat, ale my se bavíme o textu v aplikaci. Na Play s tím souhlasím, že tam nemusíme nic vysvětlovat. Já si myslím, že je dobré ty lidi trochu vychovávat. Neříkám, že jim musíme všechno vysvětlit, ale třeba zrovna o AZ by představu mít měli. Už jen proto, že si stěžují na neveřejné dokumenty a diví se, že jim to nechceme zpřístupnit. Navíc to nikomu nenutíme. Kdo se s tím bude chtít seznámit, tak se s tím seznámí. A kdo ne, tak ne. (A myslím, že to zas tak nudné není :) Najdou se lidi, které to zajímá a chtěli by se o tom něco dozvědět. A možná, že toto je jeden z mála způsobů, jak se o tom mohou dozvědět - od knihovníků třeba v aplikaci. Ale to už by byla debata na dlouho. Nemá cenu se nad tím dohadovat. Já jsem každopádně pro je nezatěžovat detaily, s tím textem souhlasím).
