### ISSUE TITLE
Nové knihovny do aplikace

### ISSUE THREAD

**Issue by LenkaDamborska** [moravianlibrary/kramerius-for-android#234]
Zájem o přidání do aplikace mají také Krajská vědecká knihovna v Liberci, Zemědělské poradensko-vzdělávací centrum a Knihovna Antonína Švehly a Digitální studovna Ministerstva obrany ČR (s touto jsi, Honzo, komunikoval). 
Pokud bys od nich něco potřeboval (třeba hezkou ikonku), tak se ozvi.

**Comment by LenkaDamborska** [comment]
Tak a ještě KNAV :)

**Comment by honza-rychtar** [comment]
Jak je to vlastne s 
"Zemědělské poradensko-vzdělávací centrum a Knihovna Antonína Švehly" a "Ústav zemědělské ekonomiky a informací" 
Kramerius jim bezi na domene uzei.cz 
Jaky je teda spravny nazev pro instituci, ktere Kramerius patri?

**Comment by LenkaDamborska** [comment]
Psala jsem jim a chtějí tam mít pouze "Knihovna Antonína Švehly", tak jim to tam, prosím, tak dej.

**Comment by honza-rychtar** [comment]
Ok, a ikonu?
http://www.uzei.cz/ 
http://www.knihovnasvehly.cz/
Odkud z tech dvou webu?

**Comment by honza-rychtar** [comment]
Pridal jsem nove knihovny a taky doplnil skryte zdroje.

### Stavajici
Moravská zemská knihovna
Národní digitální knihovna
Jihočeská vědecká knihovna
Vědecká knihovna v Olomouci
Studijní a vědecká knihovna v Hradci Králové
Městská knihovna Česká Třebová
Severočeská vědecká knihovna v Ústí nad Labem
Krajská knihovna Františka Bartoše ve Zlíně

### Nove
Digitální studovna Ministerstva obrany ČR
Národní technická knihovna
Národní filmový archiv
Krajská knihovna Karlovy Vary
Univerzita Karlova v Praze - Fakulta sociálních věd
Knihovna Akademie věd ČR
Krajská vědecká knihovna v Liberci
Knihovna Antonína Švehly
         
### Skryte   
Moravskoslezská vědecká knihovna v Ostravě
Mendelova univerzita v Brně
Židovské muzeum v Praze
Národní muzeum
Slezská univerzita v Opavě
Lesnický a myslivecký digitální archiv
Univerzitná knižnica v Bratislave
Výzkumný ústav geodetický, topografický a kartografický
Studijní a vědecká knihovna Plzeňského kraje
Knihovna Západočeského muzea v Plzni
Městská knihovna v Praze
Národní knihovna
Středočeská vědecká knihovna v Kladně
Česká digitální knihovna

Ty skryte jsou dalsi adepti.
Co MKP vlastne?

**Comment by LenkaDamborska** [comment]
Ahoj, ozvali se mi z Mendlovky, že by taky chtěli být v aplikaci. Stíhá se to ještě? Nastavili i vybrané. 

Jinak Katka Šírová z MKP mi říkala, že mají problém s logem. Nedaří se jim vyřešit, jestli bude s popiskem nebo bez (jo, je to prkotina, ale prý na to logo nemají v podstatě práva). Proto se ještě neozvali.

**Comment by honza-rychtar** [comment]
Ok, Mendlovku pridam.

Motame pojmy logo a ikona (ja taky).
Nepouzivame loga, ale ikony, tj **ctvercove** obrazky, ktere jsou dostatecne viditelne a reprezentujici i pri malem formatu.
Ikona v sobe **nesmi** mit popisek, tak at to prestanou resit :)
Konkretne MKP ma dobre logo, ktere funguje pekne jako ikona.
Tady jde videt https://registr-krameriu.herokuapp.com/
MZK, MKP super, ale NDK, Hradec Kralove, .. jako ikona nefunguje - jako velke logo nekde v hlavicce ano. ale ne jako ikona.

Pokud jde o prava, tak to je vtipne :) To at si nechaji navrhnout logo radeji znova a tentokrat s normalni smlouvou.
Ty 4 ctverecky s uvozovkouvou nozickou klidne za 30 sekund nakreslim sam a dal se budu povazovat za autora :) Stavajici autor urcite nema patent na vsechny ikony s rozparcelovanym ctvercem ...

Neni to ikona aplikace, je to jen obsah v opensource nekomercni aplikaci, takze s pravniho hlediska vas nemaji za co zalovat - maximalne muzou doporucit zmenit obrazek - a jsme zpet u toho, ze si ho nakreslim sam.

**Comment by honza-rychtar** [comment]
Pridana MKZ, celkem je tedy 17 knihoven v aplikaci.

**Comment by honza-rychtar** [comment]
Oprava, s Mendelu jich je 18
