### ISSUE TITLE
Ročník versus rok vydání

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius-for-android#242]
Navrhuji dát do záhlaví jednotlivých ročníků rok vydání a ročník dát dolů - ročník je často jen nic neříkající číslo, rok vydání je významnější.

**Comment by honza-rychtar** [comment]
U seznamu rocniku jsem prehodil rok vydani a rocnik.
U seznamu cisel jesm prehodil datum vydani a cislo.
Taky jsem umazal prefixy "ROK VYDANI: " a "DATUM VYDANI:" - kdyz je ted rok a datum v title, tak je tam prefix zbytecny.
