### ISSUE TITLE
Chybějící "vybrané" dokumenty

### ISSUE THREAD

**Issue by vjirousek** [moravianlibrary/kramerius-for-android#253]
V sekci "Mohlo by se líbit" se pod Národní knihovnou i po rozkliknutí zobrazuje pouze 5 titulů oproti 18 vybraným ve webovém klientovi. Podobného problému jsem si všiml i u některých dalších knihoven:

Severočeská vědecká knihovna v Ústí nad Labem
Knihovna Akademie věd ČR
Krajská vědecká knihovna v Liberci
Městská knihovna v Praze

**Comment by honza-rychtar** [comment]
Aplikace filtruje pouze top-level modely ve vybranych.
NKP ma 5 monografii a 13 stranek. Takze se zobrazi pouze ty monografie.
Mit ve vybranych stranku nedava smysl, resp. je to hack, ktery nekdo pouziva, aby vybral "peknejsi" reprezentativni stranku misto prvni strany.
Na webu jsem nakonec stranky ve vybranych povolil, ale ma to nekolik problemu - neni znamy autor, neni znamy typ nadrazeneho dokumentu:
http://www.digitalniknihovna.cz/nkp/

Tohle by slo opravit na urovni API, aby se vracely i tyto informace v pripade stranky. 
Ale znova upozornuju, ze jen prohlubujeme ten hack - spravne reseni je pridat do Krameria podporu vyberu repreznetujici stranky a ne to vsemozne obchazet a ohybat kvuli toho API a pet klientu ....

**Comment by honza-rychtar** [comment]
Je tam jeste jeden filtr a to ze aplikce zobrazuje pouze verejne dokumenty (to dela ten rozdil napr. u MKP). Tohle chovaji je mozne zmenit v nastaveni.

**Comment by vjirousek** [comment]
Díky, vůbec mne nenapadlo že bychom tam mohli mít odkazy přímo na stránky. Souhlasím že za této situace bych to asi dále neřešil.
