### ISSUE TITLE
nahlaseni chyb v metadatech a pozadavek o zpristupneni.

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius-for-android#98]
Soucasti API by melo byt mozne nahlasit chybu v metadatech.
Poslalo by se uuid, uzivatelska zprava a pripadne uzivatelsky email.

Taky se mel dat poslat pozadavek na zpristupneni dokumentu - pokud by si uzivatel myslel, ze dokument neni autorsky chraneny, ale v Kremeriovi pristupny neni, tak by na to mohl takto upozornit.

Tohle je spis namet na diskuzi, hned tak realizovane to asi nebude.
Mohlo by to fungovat nasledovne:
Do API by se pridaly zminene dva pozadavky. Ty by se odesilaly na konkretniho Krameria. Kramerius by pak generoval 2 seznamy (pro nahlasene chyby a pozadavky na zpristupneni), ke kterym by meli pristup jen uzivatele s dostatecnymi pravy.
Androidi i webovy klient by tyto pozadavky posilal prostrednictvim API.

**Comment by zabak** [comment]
Řeší se v #68, zde uzavírám.
